### ISSUE TITLE
source-to-image task failed - error resolving dockerfile path

### ISSUE THREAD

**Issue by maheshwarishikha** [IBM/tekton-tutorial#4]
Hi,  
I have followed all the steps as explained in this tutorial, but final step PipelineRun fails with following error.
Failed  6s    pipeline-controller  TaskRun picalc-pr-rjjnf-source-to-image-7zz4l has failed

Checked details log as: 
kubectl -n default logs picalc-pr-rjjnf-source-to-image-7zz4l-pod-f813f3 -c step-build-and-push

Log says:
Error: error resolving dockerfile path: please provide a valid path to a Dockerfile within the build context with --dockerfile

Could you please help to resolve this.
Thanks.

**Comment by qhh0205** [comment]
@maheshwarishikha The same issue for me, have you resolved now?

**Comment by GregDritschler** [comment]
The syntax for parameter references changed in Tekton 0.7 from using curly braces to parentheses.  For example ${inputs.params.pathToDockerFile} now should be $(inputs.params.pathToDockerFile).

I will be updating the tutorial but I'm waiting on the IKS add-on to be upgraded to Tekton 0.7.

**Comment by qhh0205** [comment]
@GregDritschler I use the $(inputs.params.pathToDockerFile), but still the same issue.

**Comment by maheshwarishikha** [comment]
@qhh0205 , it is working for me now.
Try using $(inputs.params.pathToDockerFile) - with a fresh setup. It might help.
