### ISSUE TITLE
typo in ibm cloud doc

### ISSUE THREAD

**Issue by alxiong** [IBM/tekton-tutorial#7]
In https://developer.ibm.com/tutorials/build-and-deploy-a-docker-image-on-kubernetes-using-tekton-pipelines/#create-a-task-to-build-an-image-and-push-it-to-a-container-registry

there is a typo, or rather missing of `kubectl apply -f `  at the front:

<img width="728" alt="Screenshot 2020-06-30 at 10 59 57 AM" src="https://user-images.githubusercontent.com/20514086/86080377-53793f00-bac5-11ea-82be-10137cfe812f.png">

**Comment by GregDritschler** [comment]
Thanks.  It's been fixed.
